- hosts: F5
  connection: httpapi

  tasks:
    - name: Create Node
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.22/mgmt/tm/ltm/node
        method: POST
        body:  
          name: "20.20.20.20"
          partition: "Common"
          address: "20.20.20.20"
        body_format: json
        headers:
          Authorization: "Basic YWRtaW46UEBzc3cwcmQxMjM="
          Accept: "application/json"
      register: __result
    - name: Create Node
      debug:
        var: __result.content