- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Get Report Configuration List
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/log/logreport.reportconfig.runnow?report={{report_name}}
        method: GET
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result
    - name: Print Report Configuration List
      debug:
        var: __result.content