- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Post Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18:90/api/v1.0/ServerObjects/Server/VirtualServer
        method: POST
        body:
          name: "VS-Test21"
          interface: "port4"
          #ipv4Address: "8.8.8.8 255.255.255.255"
          #ipv6Address: "::/0"
          enable: "true"
          vip:
            ip: "10.1.125.5\\/32"
          useInterfaceIP: "false"
          can_delete: "true"
        body_format: json
        headers:
          Authorization: "YWRtaW46UEBzc3cwcmQ="
          Accept: "application/json"
      register: __result
    - name: Print Virtual Server
      debug:
        var: __result.content