- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Post Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18:90/api/v1.0/ServerObjects/Server/VirtualServer
        method: POST
        body:
          name: "VS-Test2"
          interface: "port4"
          ipv4Address: "1.1.1.1/255.255.255.255"
          status: "true"
          useInterfaceIP: "false"
        body_format: json
        headers:
          Authorization: "YWRtaW46UEBzc3cwcmQ="
          Accept: "application/json"
      register: __result
    - name: Print Virtual Server
      debug:
        var: __result.content