- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Post Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/system/admin.administrators
        method: POST
        body: 
            data-raw:
            name: test_psi
            type: local
            password: pass
            confirmPassword: pass
            accessProfile: prof_admin
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
          #Content-Type: "multipart/form-data"
      register: __result
    - name: Print Virtual Server
      debug:
        var: __result.content