- name: INSTALL PREVIEW - POLICY PACKAGE
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  collections: fortinet.fortimanager
  vars:
    adom: root
    ppkg: DC-FW-Forti-CNI-FG-08-16_FGT-EW
    device: DC-FW-Forti-CNI-FG-08-16
    vdom: FGT-EW
  tasks:
    - name: Install for policy package {{ adom }}/{{ ppkg }} [preview mode]
      fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
             - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
      register: r
    - name: Poll the task
      fmgr_fact:
        facts:
          selector: 'task_task'
          params:
            task: '{{ r.meta.response_data.task }}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
    - name: Trigger the preview report generation for policy package {{ adom }}/{{ ppkg }}
      fmgr_securityconsole_install_preview:
        securityconsole_install_preview:
          adom: "{{ adom }}"
          device: "{{ device }}"
          flags:
            - json
          vdoms: root
      register: r
    - name: Poll the task
      fmgr_fact:
        facts:
          selector: 'task_task'
          params:
            task: '{{ r.meta.response_data.task }}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
    - name: Get the preview report for policy package {{ adom }}/{{ ppkg }}
      fmgr_securityconsole_preview_result:
        securityconsole_preview_result:
           adom: "{{ adom }}"
           device: "{{ device }}"
      register: r
    - name: Show preview report
      debug:
        msg: "{{ r }}"