- name: INSTALL PREVIEW - POLICY PACKAGE
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  collections: fortinet.fortimanager

  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    adom: "root"
    pkg: "DC-FW-Forti-CNI-FG-08-16_FGT-EW"
    device: "DC-FW-Forti-CNI-FG-08-16"
    vdom: "FGT-EW"

  tasks:
    - name: Install for policy package
      fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          pkg: "{{ pkg }}"
          scope:
            - name: "{{ device }}"
              vdom: root
      #register: r