- hosts: DC-MGT-Forti-CNI-FMG-21
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom: "root"
     pkg: "DC-FW-Forti-CNI-FG-08-16_FGT-NS"
  tasks:
   - name: Configure IPv4 policies.
     fmgr_pkg_firewall_policy:
        bypass_validation: False
        adom: "{{ adom }}"
        pkg: "{{ pkg }}" # package name
        state: present
        pkg_firewall_policy:
           action: deny #<value in [deny, accept, ipsec, ...]>
           comments: ansible-comment
           dstaddr: db_openstack1
           dstintf: port7
           name: "Deny AWS to Internal"
           nat: disable
           policyid: 1
           schedule: always
           service: "ALL_ICMP"
           srcaddr: php_aws1
           srcintf: port7
           status: disable