- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Reboot Appliance
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/system/status.systemoperationreboot
        method: POST
        body:  
            reason: "test-reboot"
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result
    - name: Print Reboot Appliance
      debug:
        var: __result.content
