- collections:
  - fortinet.fortios
  connection: httpapi
  hosts: DC-FW-Forti-CNI-FG-08-16
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    vdom: FGT-EW
  tasks:
  - name: fortios_firewall_policy
    fortios_firewall_policy:
      vdom: "{{ vdom }}"
      state: present
      firewall_policy:
        action: accept
        dstaddr: 
          - name: 'test1'
        dstintf: 
          - name: 'port3'
        name: "policy1"
        policyid: 20
        schedule: always
        service: 
          - name: 'DNS'
        srcaddr: 
          - name: 'test2'
        srcintf: 
          - name: 'port3'
        status: enable
