- collections:
  - fortinet.fortimanager
  connection: httpapi
  hosts: DC-MGT-Forti-CNI-FMG-21
  vars:
     ansible_httpapi_use_ssl: true
     ansible_httpapi_validate_certs: false
     ansible_httpapi_port: 443
  tasks:
  - name: Configure IPv4 addresses
    fmgr_firewall_address: #source
      bypass_validation: False
      adom: root
      state: present
      firewall_address:
        allow-routing: disable
        associated-interface: any
        name: 'php_aws1'
        subnet: '10.1.73.176/32'

  - name: Configure IPv4 addresses
    fmgr_firewall_address: #destination
      bypass_validation: False
      adom: root
      state: present
      firewall_address:
        allow-routing: disable
        associated-interface: any
        name: 'db_openstack1'
        subnet: '10.1.123.5/32'