- hosts: DC-MGT-Forti-CNI-FMG-21
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom: root
  tasks:
   - name: Configure custom services.
     fmgr_firewall_service_custom:
        bypass_validation: False
        adom: "{{ adom }}"
        state: present
        firewall_service_custom:
           app-service-type: disable #<value in [disable, app-id, app-category]>
           color: 1
           comment: 'Create by Ansible'
           helper: auto #<value in [disable, auto, ftp, ...]>
           name: 'tcp_9000'
           protocol: TCP/UDP/SCTP #<value in [ICMP, IP, TCP/UDP/SCTP, ...]>
           proxy: disable #<value in [disable, enable]>
           tcp-portrange: "9000"
           visibility: enable #<value in [disable, enable]>