- hosts: FortiWeb
  connection: httpapi

  vars:
    vs_name: "VS-Kontol"

  tasks:
    - name: Post Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/cmdb/server-policy/vserver
        method: POST
        body:
          name: {{vs_name}}
          enable: "true"
          useInterfaceIP: "false"
          can_delete: "true"
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result

    - name: Attach Virtual IP
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/cmdb/server-policy/vserver/vip-list?mkey={{vs_name}}
        method: POST
        body:
          vip: "testVIP1"
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result
      
    - name: Print Virtual Server
      debug:
        var: __result.content