- collections:
    - fortinet.fortimanager
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    adom: "root"
    pkg: "DC-FW-Forti-CNI-FG-08-16_FGT-EW"
    device: "DC-FW-Forti-CNI-FG-08-16"
    vdom: "FGT-EW"
  tasks:
    - name: Copy and install a policy package to devices.
      fmgr_securityconsole_install_package:
        bypass_validation: True
        securityconsole_install_package:
          adom: root
          adom_rev_comments: ansible-comment
          adom_rev_name: ansible-test
          dev_rev_comments: ansible-comment
          flags:
            - none
            - cp_all_objs
            - preview
            - generate_rev
            - copy_assigned_pkg
            - unassign
            - ifpolicy_only
            - no_ifpolicy
            - objs_only
            - auto_lock_ws
            - check_pkg_st
            - copy_only
          pkg: "{{ pkg }}"
          scope:
            -
              name: "{{ device }}"
              vdom: "{{ vdom }}"

    - name: Install policies to device from preview cache.
      #fmgr_securityconsole_install_package:
      fmgr_securityconsole_package_commit:
        bypass_validation: True
        workspace_locking_adom: "{{ adom }}"
        workspace_locking_timeout: 300
        rc_succeeded: [0, -2, -3, ...]
        rc_failed: [-2, -3, ...]
        securityconsole_package_commit:
           adom: root
           scope:
             -
                 name: "{{ device }}"
                 vdom: "{{ vdom }}"