- collections:
  - fortinet.fortimanager
  connection: httpapi
  hosts: DC-MGT-Forti-CNI-FMG-21
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
  - name: "Configure IPv4 addresses"
    fmgr_firewall_address:
      bypass_validation: False
      adom: root
      state: present
      firewall_address:
        allow-routing: disable
        associated-interface: any
        name: 'ansible-test1'
        visibility: disable