- hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  collections: 
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    adom: "root"
    pkg: "DC-FW-Forti-CNI-FG-08-16_FGT-EW"
    device: "DC-FW-Forti-CNI-FG-08-16"
    vdom: "FGT-EW"
  tasks:
    - name: INSTALL PACKAGE
      fmgr_fwpol_package:
        mode: "set"
        adom: "{{ adom }}"
        name: "{{ pkg }}"
        object_type: "install"
        scope_members: "{{ device }}"