- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Get Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/policy/serverobjects.server.virtualserver
        method: GET
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result
    - name: Print Virtual Server
      debug:
        var: __result.content