- hosts: FortiWeb
  connection: httpapi

  tasks:
    - name: Post Virtual Server
      uri:
        follow_redirects: none
        validate_certs: false
        return_content: yes
        url: https://10.1.117.18/api/v2.0/system/admin.administrators
        method: POST
        body:
          name: "psi_anton"
          type: "local"
          password: "test1234"
          confirmPassword: "test1234"
          accessProfile: "prof_admin"
          adminUserGroup: ""
          _id: "3"
        body_format: json
        headers:
          Authorization: "eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQQHNzdzByZCIsInZkb20iOiJyb290In0="
          Accept: "application/json"
      register: __result
    - name: Print Virtual Server
      debug:
        var: __result.content