- name: INSTALL PREVIEW - POLICY PACKAGE
  hosts: DC-MGT-Forti-CNI-FMG-21
  connection: httpapi
  collections: fortinet.fortimanager
  vars:
    adom: root
    ppkg: DC-FW-Forti-CNI-FG-08-16_FGT-EW
    device: DC-FW-Forti-CNI-FG-08-16
    vdom: FGT-EW
  tasks:
    - name: Install for policy package {{ adom }}/{{ ppkg }}
      fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
             - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
      register: r